import type { Tone } from './destinations';
import type { Collection } from './collections';

export const HONEYMOON_COLLECTIONS: Collection[] = [
  {
    slug: "from-mumbai",
    h1: "Kashmir Honeymoon Packages from Mumbai",
    seoTitle: "Kashmir Honeymoon Packages from Mumbai | Glitz Holidays",
    metaDescription: "Romantic Kashmir honeymoon packages from Mumbai: direct 2h 45m flights, candlelit Dal Lake shikara rides, luxury Gulmarg heating, and snow suites. Updated 2026.",
    kicker: "Mumbai to Kashmir Honeymoon",
    lede: "From the Arabian Sea to snow-draped Pir Panjal peaks in under 3 hours. Handcrafted itineraries for Mumbai couples with premium heating and private mountain transfers.",
    crumbLabel: "Honeymoon from Mumbai",
    demand: { queries: 110, impressions: 997, conversions: 2.0 },
    body: ["Mumbai couples benefit from daily non-stop flights from Chhatrapati Shivaji Maharaj International Airport (BOM) to Srinagar (SXR), landing in just 2 hours 45 minutes.", "We pair romantic stays across luxury heated houseboats on Nigeen Lake with pine-view boutique chalets in Gulmarg and riverside suites in Pahalgam.", "Every honeymoon package includes private transfers in an immaculate sedan or 4x4, flower bed decor, candlelight dinners, and customized couple photography spots."],
    packages: ["kashmir-honeymoon-5-nights", "complete-kashmir-6-nights", "classic-kashmir-4-nights"],
    faqs: [{"q": "How long is the flight from Mumbai to Srinagar for a honeymoon?", "a": "Direct flights from Mumbai (BOM) to Srinagar (SXR) take approximately 2 hours 45 minutes to 3 hours 15 minutes."}, {"q": "What special inclusions are provided for honeymoon couples from Mumbai?", "a": "Our packages include private heated shikara rides, welcome Kashmiri Kehwa, almond-saffron milk, flower bed decoration on Day 1, and candlelit dinners."}, {"q": "Which is the best season for a Kashmir honeymoon from Mumbai?", "a": "April\u2013May for blooming gardens, September\u2013October for golden Chinar trees and clear skies, and January\u2013February for deep snow and skiing in Gulmarg."}, {"q": "Do hotels in Kashmir provide central heating in winter?", "a": "Yes, our honeymoon properties in Gulmarg, Pahalgam, and Srinagar are equipped with central heating, electric heating blankets, and traditional bukharis."}],
    tone: "kashmir",
    basePath: '/packages/honeymoon',
  },
  {
    slug: "from-bangalore",
    h1: "Kashmir Honeymoon Packages from Bangalore",
    seoTitle: "Kashmir Honeymoon Packages from Bangalore | Glitz Holidays",
    metaDescription: "Kashmir honeymoon packages from Bangalore: direct flights from BLR, romantic Dal Lake houseboats, private snow cabs, and heated chalets. Updated 2026.",
    kicker: "Bangalore to Kashmir Honeymoon",
    lede: "Escape the Silicon Valley rush for misty Himalayan lakes and snow-covered pines. Handpicked luxury honeymoon tours for Bangalore couples.",
    crumbLabel: "Honeymoon from Bangalore",
    demand: { queries: 95, impressions: 805, conversions: 4.0 },
    body: ["Bangalore couples enjoy direct flights from Kempegowda International Airport (BLR) to Srinagar (SXR) taking just 3 hours 15 minutes, with additional convenient 1-stop options via Delhi.", "We structure Day 1 for relaxed acclimatization\u2014arriving in Srinagar with ample afternoon light for a quiet private Shikara sunset across the lotus canals of Nigeen Lake.", "Enjoy romantic alpine walks in Betaab Valley, Gondola rides to Apharwat Peak, and cozy evenings by a wood-burning fireplace."],
    packages: ["kashmir-honeymoon-5-nights", "complete-kashmir-6-nights", "classic-kashmir-4-nights"],
    faqs: [{"q": "Are there direct flights from Bangalore to Srinagar?", "a": "Yes, IndiGo and Air India operate daily direct flights (3h 15m) as well as 1-stop flights via New Delhi."}, {"q": "What is the ideal duration for a Kashmir honeymoon from Bangalore?", "a": "5 Nights / 6 Days or 6 Nights / 7 Days is the perfect balance to cover Srinagar, Gulmarg, Pahalgam, and Sonmarg without travel fatigue."}, {"q": "How is food catered for South Indian couples in Kashmir?", "a": "Our partner luxury resorts and houseboats serve a blend of Kashmiri Wazwan, North Indian, South Indian breakfast options, and pure vegetarian meals upon request."}, {"q": "Is Gulmarg Gondola ticket booking included in the honeymoon package?", "a": "Yes, we arrange confirmed Phase 1 and Phase 2 Gondola tickets in advance to save couples from long on-ground ticket queues."}],
    tone: "kashmir",
    basePath: '/packages/honeymoon',
  },
  {
    slug: "from-chennai",
    h1: "Kashmir Honeymoon Packages from Chennai",
    seoTitle: "Kashmir Honeymoon Packages from Chennai | Glitz Holidays",
    metaDescription: "Romantic Kashmir honeymoon packages from Chennai: flight connectivity, luxury houseboats, snow suites in Gulmarg, and romantic dining. Updated 2026.",
    kicker: "Chennai to Kashmir Honeymoon",
    lede: "From the Coromandel coast to the snow-crowned Himalayas. Expertly curated romantic holidays with complete heating and private chauffeured cars.",
    crumbLabel: "Honeymoon from Chennai",
    demand: { queries: 78, impressions: 654, conversions: 3.0 },
    body: ["Chennai couples can fly seamlessly from Chennai International Airport (MAA) to Srinagar (SXR) with daily 1-stop and seasonal direct connections.", "Experience the romance of staying in a carved cedar houseboat, riding the world's highest gondola at Gulmarg, and listening to the rushing waters of the Lidder River in Pahalgam.", "Our Srinagar operations team manages all logistics on the ground, ensuring private airport pickups, reliable heating, and personalized excursion planning."],
    packages: ["kashmir-honeymoon-5-nights", "complete-kashmir-6-nights"],
    faqs: [{"q": "What is the best flight connection from Chennai to Srinagar?", "a": "Morning flights with a 1.5 to 2 hour layover in Delhi or Mumbai ensure you arrive in Srinagar by early afternoon."}, {"q": "Is Kashmir cold for couples visiting from Chennai?", "a": "In winter (Dec\u2013Feb), temperatures drop below freezing, but all our honeymoon rooms are fully heated with electric blankets. Spring and autumn are mild and pleasant (15\u00b0C\u201322\u00b0C)."}, {"q": "What romantic activities are included in the package?", "a": "Sunset Shikara ride on Dal Lake, romantic dinner in a pine-view chalet, couple photoshoot in traditional Kashmiri Pheran, and Gondola rides."}, {"q": "Can we customize our itinerary?", "a": "Yes, our team tailors the pace, destinations, and hotel categories strictly to your preferences."}],
    tone: "kashmir",
    basePath: '/packages/honeymoon',
  },
  {
    slug: "from-pune",
    h1: "Kashmir Honeymoon Packages from Pune",
    seoTitle: "Kashmir Honeymoon Packages from Pune | Glitz Holidays",
    metaDescription: "Kashmir honeymoon packages from Pune: flight connections, luxury heated houseboats, Gulmarg skiing, and romantic Pahalgam stays. Updated 2026.",
    kicker: "Pune to Kashmir Honeymoon",
    lede: "Leave the Sahyadris behind for the Great Himalayas. Romantic honeymoon packages designed for Pune couples seeking beauty, luxury, and tranquility.",
    crumbLabel: "Honeymoon from Pune",
    demand: { queries: 88, impressions: 783, conversions: 2.0 },
    body: ["Pune couples can fly directly from Pune International Airport (PNQ) or take direct flights via Mumbai/Delhi to arrive in Srinagar in under 4 hours.", "Enjoy handpicked heritage stays on Nigeen Lake, private pony excursions to Baisaran meadow, and cozy evenings in snow-covered Gulmarg chalets.", "Complete with candlelit dining, private 4x4 transport, and 24/7 on-ground support from our Srinagar headquarters."],
    packages: ["kashmir-honeymoon-5-nights", "complete-kashmir-6-nights", "classic-kashmir-4-nights"],
    faqs: [{"q": "Are there direct flights from Pune to Srinagar?", "a": "Yes, direct flights operate seasonally, along with daily 1-stop flights via Delhi and Mumbai."}, {"q": "How many days are recommended for a honeymoon from Pune?", "a": "5 to 6 nights allow you to explore Srinagar, Gulmarg, Pahalgam, and Sonmarg at a leisurely, romantic pace."}, {"q": "What is included in the honeymoon welcome package?", "a": "Flower bed decoration on arrival night, complimentary honeymoon cake, special candlelit dinner, and fresh Kashmiri Kehwa."}, {"q": "Is winter snow guaranteed in Gulmarg?", "a": "Gulmarg receives heavy, consistent snowfall from late December through February, offering ideal snow conditions for couples."}],
    tone: "kashmir",
    basePath: '/packages/honeymoon',
  },
  {
    slug: "from-ahmedabad",
    h1: "Kashmir Honeymoon Packages from Ahmedabad",
    seoTitle: "Kashmir Honeymoon Packages from Ahmedabad | Glitz Holidays",
    metaDescription: "Romantic Kashmir honeymoon packages from Ahmedabad: direct flights, pure-vegetarian & Jain food, luxury houseboats, and snow chalets. Updated 2026.",
    kicker: "Ahmedabad to Kashmir Honeymoon",
    lede: "Direct 2h 15m flights from AMD to SXR. Handcrafted honeymoon packages for Gujarat couples with vetted pure-vegetarian and Jain meal arrangements.",
    crumbLabel: "Honeymoon from Ahmedabad",
    demand: { queries: 70, impressions: 580, conversions: 2.0 },
    body: ["Ahmedabad couples enjoy direct non-stop flights from Sardar Vallabhbhai Patel International Airport (AMD) to Srinagar (SXR) in just 2 hours 15 minutes.", "We understand dietary preferences: our honeymoon itineraries guarantee authentic, pure-vegetarian and Jain dining across all luxury hotels and houseboats.", "From romantic Shikara rides on Dal Lake to breathtaking Gondola journeys over snow-capped Apharwat Peak, every moment is curated for couple comfort."],
    packages: ["kashmir-honeymoon-5-nights", "complete-kashmir-6-nights", "classic-kashmir-4-nights"],
    faqs: [{"q": "Are pure Jain meals available on the Kashmir honeymoon trip?", "a": "Yes, we coordinate directly with our partner hotels and houseboats to provide pure Jain food prepared without onion, garlic, or root vegetables."}, {"q": "How long is the direct flight from Ahmedabad to Srinagar?", "a": "Direct non-stop flights from Ahmedabad (AMD) take approximately 2 hours 15 minutes to reach Srinagar (SXR)."}, {"q": "Which places are best for couple photoshoots?", "a": "Mughal Gardens (Nishat & Shalimar), Betaab Valley riverbanks, Baisaran 'Mini Switzerland', and Gulmarg Apharwat snow ridge."}, {"q": "Do we get private transportation throughout the tour?", "a": "Yes, you have an exclusive dedicated vehicle (Sedan/Innova/4x4) with a professional driver from airport arrival to departure."}],
    tone: "kashmir",
    basePath: '/packages/honeymoon',
  },
  {
    slug: "from-kolkata",
    h1: "Kashmir Honeymoon Packages from Kolkata",
    seoTitle: "Kashmir Honeymoon Packages from Kolkata | Glitz Holidays",
    metaDescription: "Kashmir honeymoon packages from Kolkata: direct 3h flights from CCU, heritage houseboats on Nigeen lake, and snow suites in Gulmarg. Updated 2026.",
    kicker: "Kolkata to Kashmir Honeymoon",
    lede: "Fly from the City of Joy to the paradise of Kashmir in 3 hours. Romantic houseboats, pine chalets, and private mountain drives for Kolkata couples.",
    crumbLabel: "Honeymoon from Kolkata",
    demand: { queries: 45, impressions: 362, conversions: 1.0 },
    body: ["Direct and 1-stop flights from Netaji Subhash Chandra Bose International Airport (CCU) connect Kolkata couples to Srinagar (SXR) in roughly 3 hours.", "Stay in cedar-scented luxury houseboats on peaceful Nigeen Lake, ride the Gondola above the clouds in Gulmarg, and stroll through saffron fields in Pampore.", "Complete with floral room decor, candlelit dinners, private chauffeured vehicles, and dedicated 24/7 on-ground assistance."],
    packages: ["kashmir-honeymoon-5-nights", "complete-kashmir-6-nights"],
    faqs: [{"q": "How long does the flight take from Kolkata to Srinagar?", "a": "Direct flights take about 3 hours; 1-stop flights via Delhi take approximately 5 to 6 hours total transit time."}, {"q": "Which is more romantic: Dal Lake or Nigeen Lake houseboats?", "a": "Nigeen Lake is quieter, more secluded, and surrounded by willow trees, making it our top recommendation for honeymoon couples."}, {"q": "Is a trip to Sonmarg included in the 5-night honeymoon?", "a": "Yes, a scenic day excursion to Sonmarg and Thajiwas Glacier is included in our 5-night and 6-night honeymoon plans."}, {"q": "What documents are required for travelling to Kashmir?", "a": "Indian citizens only need a valid government photo ID (Aadhaar, Passport, or Voter ID) for flight boarding and hotel check-in."}],
    tone: "kashmir",
    basePath: '/packages/honeymoon',
  },
  {
    slug: "from-chandigarh",
    h1: "Kashmir Honeymoon Packages from Chandigarh",
    seoTitle: "Kashmir Honeymoon Packages from Chandigarh | Glitz Holidays",
    metaDescription: "Quick 1-hour flight from IXC to Srinagar. Romantic Kashmir honeymoon packages from Chandigarh with luxury heated stays and snow suites. Updated 2026.",
    kicker: "Chandigarh to Kashmir Honeymoon",
    lede: "Just a 65-minute flight from Chandigarh to Srinagar. The fastest mountain getaway for Punjab and Tricity honeymooners.",
    crumbLabel: "Honeymoon from Chandigarh",
    demand: { queries: 25, impressions: 138, conversions: 1.0 },
    body: ["Chandigarh couples enjoy the fastest flight connection in India: direct non-stop flights from Shaheed Bhagat Singh Airport (IXC) reach Srinagar (SXR) in just 1 hour 05 minutes.", "Arriving before noon allows you to maximize your first day with an afternoon Shikara cruise on Dal Lake followed by a romantic Mughal garden walk.", "Handpicked 4-night and 5-night itineraries covering snow sports in Gulmarg, riverside serenity in Pahalgam, and heritage stays in Srinagar."],
    packages: ["classic-kashmir-4-nights", "kashmir-honeymoon-5-nights"],
    faqs: [{"q": "How long is the flight from Chandigarh to Srinagar?", "a": "Direct flights take only 1 hour 05 minutes, making it the quickest flight route to Kashmir."}, {"q": "Can we drive from Chandigarh to Srinagar instead of flying?", "a": "Yes, the driving distance is 565 km (11\u201313 hours). However, flying is strongly recommended for honeymooners to save time and energy."}, {"q": "What honeymoon special touches are provided?", "a": "Complimentary room decoration, welcome almond tea, special couple candlelit dinner, and private chauffeur service."}, {"q": "When is the best time for snow for Chandigarh couples?", "a": "January and February offer the deepest snow in Gulmarg and Pahalgam."}],
    tone: "kashmir",
    basePath: '/packages/honeymoon',
  },
  {
    slug: "from-jaipur",
    h1: "Kashmir Honeymoon Packages from Jaipur",
    seoTitle: "Kashmir Honeymoon Packages from Jaipur | Glitz Holidays",
    metaDescription: "Kashmir honeymoon packages from Jaipur: direct flights from JAI, pure-veg dining, luxury houseboats, and romantic snow chalets. Updated 2026.",
    kicker: "Jaipur to Kashmir Honeymoon",
    lede: "From royal desert palaces to snow-crowned Himalayan valleys. Handcrafted honeymoon packages for Rajasthan couples with pure vegetarian catering.",
    crumbLabel: "Honeymoon from Jaipur",
    demand: { queries: 45, impressions: 387, conversions: 2.0 },
    body: ["Jaipur couples can take direct and 1-stop flights from Jaipur International Airport (JAI) to Srinagar (SXR) in under 2 to 4 hours.", "Experience the contrast of cool alpine breezes, blooming tulip gardens, pine-scented valleys, and romantic wooden houseboats on Dal Lake.", "Vetted pure-vegetarian catering, private 4x4 transfers in snow zones, and 24/7 on-ground guest coordination."],
    packages: ["kashmir-honeymoon-5-nights", "complete-kashmir-6-nights"],
    faqs: [{"q": "How long does the flight take from Jaipur to Srinagar?", "a": "Direct flights take 1 hour 45 minutes; 1-stop flights via Delhi take approximately 3.5 to 4 hours."}, {"q": "Are pure vegetarian meals guaranteed for Jaipur couples?", "a": "Yes, we ensure all meal plans feature authentic North Indian pure-vegetarian food across our partner hotels and houseboats."}, {"q": "Can we add Gulmarg Gondola Phase 2 to our package?", "a": "Yes, we can pre-book both Phase 1 and Phase 2 tickets so you can reach Apharwat Peak at 13,780 ft without queuing."}, {"q": "What is the best month to visit for a honeymoon from Jaipur?", "a": "April to June for escaping summer heat into green valleys, and December to February for a fairytale snow holiday."}],
    tone: "kashmir",
    basePath: '/packages/honeymoon',
  },
  {
    slug: "from-lucknow",
    h1: "Kashmir Honeymoon Packages from Lucknow",
    seoTitle: "Kashmir Honeymoon Packages from Lucknow | Glitz Holidays",
    metaDescription: "Romantic Kashmir honeymoon packages from Lucknow: flights from LKO, heated houseboats, Awadhi comfort, and Gulmarg snow suites. Updated 2026.",
    kicker: "Lucknow to Kashmir Honeymoon",
    lede: "Fly from the City of Nawabs to the crown of Kashmir. Luxurious honeymoon packages for UP couples featuring private transfers and heated stays.",
    crumbLabel: "Honeymoon from Lucknow",
    demand: { queries: 15, impressions: 70, conversions: 1.0 },
    body: ["Lucknow couples can take direct or quick 1-stop flights from Chaudhary Charan Singh International Airport (LKO) to Srinagar (SXR) in roughly 2 to 4 hours.", "Enjoy romantic stays on Dal Lake, strolls through Shalimar and Nishat Mughal Gardens, and pine-scented trails along the Lidder River in Pahalgam.", "Complete with flower bed styling, candlelit dinners, private chauffeured cars, and round-the-clock local operations support."],
    packages: ["kashmir-honeymoon-5-nights", "complete-kashmir-6-nights"],
    faqs: [{"q": "How long is the flight from Lucknow to Srinagar?", "a": "Direct flights take 1 hour 50 minutes; flights connecting via Delhi take about 4 hours total."}, {"q": "What are the key romantic highlights in Kashmir?", "a": "Sunset Shikara ride on Dal Lake, riding the Gulmarg Gondola, walking through Betaab Valley, and dining in a cozy heated wooden chalet."}, {"q": "Are airport transfers included?", "a": "Yes, private airport pickup and drop-off at Srinagar International Airport (SXR) are included in all packages."}, {"q": "Can we combine Vaishno Devi with our honeymoon?", "a": "Yes, we offer custom 7-night itineraries combining Katra (Vaishno Devi) with Kashmir via the new direct rail link."}],
    tone: "kashmir",
    basePath: '/packages/honeymoon',
  },
  {
    slug: "from-nagpur",
    h1: "Kashmir Honeymoon Packages from Nagpur",
    seoTitle: "Kashmir Honeymoon Packages from Nagpur | Glitz Holidays",
    metaDescription: "Kashmir honeymoon packages from Nagpur: flight connections, luxury heated houseboats, Gulmarg snow chalets, and private cabs. Updated 2026.",
    kicker: "Nagpur to Kashmir Honeymoon",
    lede: "Fly from the heart of India to the snow-draped valleys of Kashmir. Romantic couple escapes tailored for Vidarbha travellers.",
    crumbLabel: "Honeymoon from Nagpur",
    demand: { queries: 35, impressions: 227, conversions: 2.0 },
    body: ["Nagpur couples can fly from Dr. Babasaheb Ambedkar International Airport (NAG) to Srinagar (SXR) via Delhi or Mumbai in 4 to 5 hours.", "We take care of every detail: heated suites, candlelit dining, private scenic drives, and confirmed Gondola and pony ride bookings.", "Experience the romance of cedar houseboats on Nigeen Lake and luxury riverside chalets in Pahalgam."],
    packages: ["kashmir-honeymoon-5-nights", "complete-kashmir-6-nights"],
    faqs: [{"q": "What is the best flight route from Nagpur to Srinagar?", "a": "Morning connecting flights via Delhi (DEL) provide the smoothest connection, landing in Srinagar around 1:00 PM."}, {"q": "Is central heating available in hotels?", "a": "Yes, all our honeymoon accommodations feature full central heating or electric blankets for cozy winter nights."}, {"q": "What is the cancellation policy for honeymoon packages?", "a": "We offer flexible date-rescheduling and transparent refund terms outlined in our published cancellation policy."}, {"q": "Can we hire traditional Kashmiri outfits for couple photos?", "a": "Yes, traditional Kashmiri Pheran and jewelry photo rentals are easily arranged at Dal Lake and Gulmarg."}],
    tone: "kashmir",
    basePath: '/packages/honeymoon',
  },
  {
    slug: "from-dehradun",
    h1: "Kashmir Honeymoon Packages from Dehradun",
    seoTitle: "Kashmir Honeymoon Packages from Dehradun | Glitz Holidays",
    metaDescription: "Romantic Kashmir honeymoon packages from Dehradun: flight connections from DED, Dal Lake houseboats, and Gulmarg snow chalets. Updated 2026.",
    kicker: "Dehradun to Kashmir Honeymoon",
    lede: "From the Garhwal foothills to the grand Kashmir Valley. Romantic bespoke packages with luxury heating and private mountain transfers.",
    crumbLabel: "Honeymoon from Dehradun",
    demand: { queries: 20, impressions: 91, conversions: 0.0 },
    body: ["Dehradun couples can easily connect from Jolly Grant Airport (DED) via Delhi to Srinagar (SXR) in roughly 3.5 to 4.5 hours.", "Enjoy the tranquility of Nigeen Lake, private Shikara rides through floating gardens, and alpine snow experiences at Apharwat Peak in Gulmarg.", "Complete with floral welcome, candlelit dinners, and dedicated local guide assistance."],
    packages: ["classic-kashmir-4-nights", "kashmir-honeymoon-5-nights"],
    faqs: [{"q": "How long does it take to travel from Dehradun to Srinagar?", "a": "Connecting flights via Delhi take approximately 3.5 to 4.5 hours total transit time."}, {"q": "What makes Kashmir different from Uttarakhand hill stations?", "a": "Kashmir offers unique expansive alpine meadows (Gulmarg/Sonmarg), living on wooden houseboats on Dal Lake, and the world's highest operational cable car."}, {"q": "When is the best season for snow in Gulmarg?", "a": "Late December through February provides reliable, deep powder snow."}, {"q": "Are all entry tickets included in the package?", "a": "We can include Mughal Gardens, Betaab Valley, and Gondola tickets directly in your package voucher."}],
    tone: "kashmir",
    basePath: '/packages/honeymoon',
  },
  {
    slug: "from-vadodara",
    h1: "Kashmir Honeymoon Packages from Vadodara",
    seoTitle: "Kashmir Honeymoon Packages from Vadodara | Glitz Holidays",
    metaDescription: "Kashmir honeymoon packages from Vadodara: flight connections, pure-veg and Jain dining, luxury houseboats, and snow chalets. Updated 2026.",
    kicker: "Vadodara to Kashmir Honeymoon",
    lede: "Curated honeymoon packages for Vadodara couples with guaranteed pure vegetarian food, private mountain cars, and heated luxury rooms.",
    crumbLabel: "Honeymoon from Vadodara",
    demand: { queries: 15, impressions: 26, conversions: 1.0 },
    body: ["Vadodara couples can fly from Vadodara Airport (BDQ) via Delhi or Mumbai to arrive in Srinagar (SXR) within 4 to 5 hours.", "We cater strictly to your dietary needs with authentic pure-veg and Jain food options at every stage of the journey.", "From romantic Dal Lake Shikara cruises to Apharwat snow adventures, your honeymoon is backed by our local Srinagar operations team."],
    packages: ["kashmir-honeymoon-5-nights", "complete-kashmir-6-nights"],
    faqs: [{"q": "How are meals arranged for vegetarian/Jain couples from Vadodara?", "a": "We partner with trusted vegetarian and Jain friendly kitchens across Srinagar, Gulmarg, and Pahalgam."}, {"q": "What is the best flight route from Vadodara to Srinagar?", "a": "Flights connecting via New Delhi (DEL) provide the shortest layovers and earliest arrival times in Srinagar."}, {"q": "Is Gulmarg safe and comfortable in winter?", "a": "Yes, our selected luxury hotels provide 24/7 central heating, electric heating blankets, and snow-ready 4x4 transport."}, {"q": "Can we get a private car throughout the trip?", "a": "Yes, a private dedicated sedan or SUV is assigned exclusively to you for the entire duration."}],
    tone: "kashmir",
    basePath: '/packages/honeymoon',
  },
  {
    slug: "srinagar",
    h1: "Srinagar Honeymoon Packages",
    seoTitle: "Srinagar Honeymoon Packages \u2014 Luxury Houseboats & Stays",
    metaDescription: "Romantic Srinagar honeymoon packages: luxury cedar houseboats on Nigeen lake, sunset Shikara rides, Mughal gardens, and candlelit Wazwan dinners. Updated 2026.",
    kicker: "Romantic Srinagar Escapes",
    lede: "Carved cedar houseboats, misty morning lake rides, and terraced Mughal gardens. Handcrafted honeymoon itineraries focused on the romance of Srinagar.",
    crumbLabel: "Srinagar Honeymoon",
    demand: { queries: 120, impressions: 756, conversions: 4.0 },
    body: ["Srinagar is the heart of any Kashmiri romantic escape. Stay in premium handcrafted houseboats on Nigeen Lake\u2014away from the commercial bustle of Boulevard road.", "Glide past floating lotus gardens during sunset in a private, heated Shikara dressed in traditional cushions and rugs.", "Explore the romantic terraced waterways of Nishat and Shalimar Bagh, Badamwari almond groves, and atmospheric Old City craft studios."],
    packages: ["classic-kashmir-4-nights", "kashmir-honeymoon-5-nights", "srinagar-packages"],
    faqs: [{"q": "Which lake is best for a honeymoon stay: Dal Lake or Nigeen Lake?", "a": "Nigeen Lake is far more peaceful, secluded, and romantic with cleaner waters and less boat traffic than commercial Dal Lake."}, {"q": "Are houseboats warm enough during winter months?", "a": "Yes, our luxury houseboats feature central heating, electric heating blankets, and cozy wood-burning bukharis."}, {"q": "What special experiences are included in Srinagar for couples?", "a": "Private sunset Shikara tour, flower-decorated room on arrival, candlelit traditional dinner, and guided heritage garden walks."}, {"q": "How many nights should we spend in Srinagar on our honeymoon?", "a": "We recommend 2 to 3 nights in Srinagar (including 1 or 2 nights on a luxury houseboat) combined with nights in Gulmarg and Pahalgam."}],
    tone: "kashmir",
    basePath: '/packages/honeymoon',
  },
  {
    slug: "pahalgam",
    h1: "Pahalgam Honeymoon Packages",
    seoTitle: "Pahalgam Honeymoon Packages \u2014 Riverside Luxury Stays",
    metaDescription: "Romantic Pahalgam honeymoon packages: luxury riverside pine resorts, Betaab valley walks, Aru valley pony trails, and private Lidder dining. Updated 2026.",
    kicker: "Pahalgam Romantic Getaway",
    lede: "Rushing glacial streams, dense pine forests, and emerald alpine meadows. The ultimate romantic sanctuary in the Lidder Valley.",
    crumbLabel: "Pahalgam Honeymoon",
    demand: { queries: 18, impressions: 27, conversions: 0.0 },
    body: ["Pahalgam at 2,130 m offers the most tranquil alpine setting for couples in Kashmir.", "Stay in boutique riverside resorts where you wake up to the sound of the Lidder River and sweeping views of pine-clad slopes.", "Visit the iconic filming locations of Betaab Valley, take romantic horse rides to Baisaran meadow ('Mini Switzerland'), and explore the rustic quiet of Aru Valley."],
    packages: ["kashmir-honeymoon-5-nights", "complete-kashmir-6-nights"],
    faqs: [{"q": "What makes Pahalgam so popular for honeymoon couples?", "a": "Pahalgam offers quiet pine forests, scenic riverside walks along the Lidder River, and intimate boutique resorts away from city crowds."}, {"q": "How do we visit Betaab Valley and Aru Valley?", "a": "We arrange a dedicated local Pahalgam union taxi (~\u20b92,200) for a seamless tour of Aru Valley, Betaab Valley, and Chandanwari."}, {"q": "What is Baisaran 'Mini Switzerland'?", "a": "Baisaran is a lush hilltop meadow 5 km from Pahalgam, accessible by a scenic 45-minute pony ride or scenic hike through pine woods."}, {"q": "How far is Pahalgam from Srinagar Airport?", "a": "Pahalgam is 90 km south-east of Srinagar, taking approximately 2.5 to 3 hours by private car via NH44."}],
    tone: "kashmir",
    basePath: '/packages/honeymoon',
  },
  {
    slug: "4-nights",
    h1: "4 Nights Kashmir Honeymoon Package",
    seoTitle: "4 Nights Kashmir Honeymoon Package | Glitz Holidays",
    metaDescription: "4 nights / 5 days Kashmir honeymoon itinerary: Srinagar luxury houseboat, Gulmarg snow gondola, and romantic Pahalgam valleys. From \u20b919,500/couple. Updated 2026.",
    kicker: "4 Nights / 5 Days Honeymoon",
    lede: "The perfect short romantic getaway. 4 nights covering Srinagar's iconic houseboats, Gulmarg's snow peaks, and Pahalgam's pine valleys without rushing.",
    crumbLabel: "4 Nights Honeymoon",
    demand: { queries: 18, impressions: 33, conversions: 1.0 },
    body: ["Our 4 Nights / 5 Days honeymoon package is designed for couples with limited leave who want the quintessential Kashmir romantic experience.", "Itinerary breakdown: 1 Night in a luxury Nigeen Lake houseboat, 1 Night in a Gulmarg snow chalet, 1 Night in a Pahalgam riverside resort, and 1 final Night in Srinagar.", "Includes private chauffeured car, Shikara ride, room flower decoration, candlelit dinner, and breakfast & dinner daily."],
    packages: ["classic-kashmir-4-nights", "kashmir-honeymoon-5-nights"],
    faqs: [{"q": "What is the day-by-day plan for a 4-night Kashmir honeymoon?", "a": "Day 1: Srinagar arrival & luxury houseboat stay; Day 2: Gulmarg Gondola & snow chalet; Day 3: Pahalgam valley & riverside resort; Day 4: Mughal Gardens & Srinagar; Day 5: Airport departure."}, {"q": "Is 4 nights enough to see Kashmir?", "a": "Yes, 4 nights is ideal for a focused romantic trip covering Srinagar, Gulmarg, and Pahalgam if flights are booked for early arrival on Day 1."}, {"q": "What is the starting price for a 4-night honeymoon package?", "a": "Starting from \u20b919,500 per person on twin-sharing basis, including luxury hotels, private car, and meals."}, {"q": "Can we add Sonmarg to a 4-night itinerary?", "a": "In 4 nights, adding Sonmarg makes the schedule rushed. We recommend saving Sonmarg for a 5-night or 6-night tour."}],
    tone: "kashmir",
    basePath: '/packages/honeymoon',
  },
  {
    slug: "5-nights",
    h1: "5 Nights Kashmir Honeymoon Package",
    seoTitle: "5 Nights Kashmir Honeymoon Package | Glitz Holidays",
    metaDescription: "5 nights / 6 days Kashmir honeymoon itinerary: 2N Srinagar houseboat, 1N Gulmarg chalet, 2N Pahalgam riverside resort. GST inclusive. Updated 2026.",
    kicker: "5 Nights / 6 Days Honeymoon",
    lede: "Our most popular couple itinerary. 5 nights balancing leisurely stays across Srinagar, the snow peaks of Gulmarg, and the pine forests of Pahalgam.",
    crumbLabel: "5 Nights Honeymoon",
    demand: { queries: 12, impressions: 15, conversions: 0.0 },
    body: ["The 5 Nights / 6 Days honeymoon is our gold-standard romantic itinerary, chosen by over 60% of our honeymoon guests.", "It provides two nights in Pahalgam to truly unwind by the Lidder River, alongside romantic stays in Gulmarg and a luxury cedar houseboat in Srinagar.", "Full inclusions: private dedicated sedan/SUV, candlelit dinner with cake, flower bed decoration, Shikara tour, and daily breakfast & dinner."],
    packages: ["kashmir-honeymoon-5-nights", "complete-kashmir-6-nights"],
    faqs: [{"q": "Why is 5 nights the recommended duration for a honeymoon?", "a": "5 nights allows you to spend 2 full nights in Pahalgam without checking in and out every morning, creating a relaxed romantic pace."}, {"q": "What destinations are included in 5 nights?", "a": "Srinagar (Dal Lake & Mughal Gardens), Gulmarg (Apharwat Gondola), Pahalgam (Betaab & Aru valleys), and an optional day trip to Sonmarg."}, {"q": "Is breakfast and dinner included in the package?", "a": "Yes, all our honeymoon packages include daily buffet breakfast and dinner at the hotels."}, {"q": "How can we book this package?", "a": "Contact our Srinagar team via WhatsApp or enquiry form with your travel dates to receive a live customized quote."}],
    tone: "kashmir",
    basePath: '/packages/honeymoon',
  },
  {
    slug: "7-nights",
    h1: "7 Nights Kashmir Honeymoon Package",
    seoTitle: "7 Nights Kashmir Honeymoon Package | Glitz Holidays",
    metaDescription: "7 nights / 8 days grand Kashmir honeymoon: Srinagar, Gulmarg, Pahalgam, Sonmarg, and Doodhpathri. Luxury stays & private cars. Updated 2026.",
    kicker: "7 Nights / 8 Days Grand Honeymoon",
    lede: "The complete, unhurried Himalayan romantic journey. 7 nights covering all five valleys: Srinagar, Gulmarg, Pahalgam, Sonmarg, and Doodhpathri.",
    crumbLabel: "7 Nights Honeymoon",
    demand: { queries: 14, impressions: 22, conversions: 0.0 },
    body: ["For couples who want the ultimate luxury experience without compromising on time, our 7 Nights / 8 Days package covers the entire valley.", "Stay in heritage houseboats, luxury ski chalets, and secluded pine lodges, with dedicated time for white-water rafting, Gondola rides, and offbeat picnics in Doodhpathri.", "Includes all private transfers, candlelight dinners, couple spa sessions (at select 5-star properties), and full concierge support."],
    packages: ["complete-kashmir-6-nights", "kashmir-honeymoon-5-nights"],
    faqs: [{"q": "What valleys are covered in a 7-night honeymoon?", "a": "Srinagar (2N), Gulmarg (2N), Pahalgam (2N), and Sonmarg / Doodhpathri (1N)."}, {"q": "Is Doodhpathri included in the 7-night tour?", "a": "Yes, Doodhpathri ('Valley of Milk') is included as a pristine, uncrowded meadow excursion."}, {"q": "Can we upgrade to 5-star luxury resorts like Khyber or Radisson?", "a": "Yes, we offer luxury tier upgrades including The Khyber Himalayan Resort in Gulmarg and premium heritage houseboats."}, {"q": "Are all honeymoon special amenities included?", "a": "Yes: floral bed styling, candlelit dinners, welcome Kehwa, custom cake, and private shikara ride."}],
    tone: "kashmir",
    basePath: '/packages/honeymoon',
  },
];

export function getHoneymoonCollection(slug: string): Collection | undefined {
  return HONEYMOON_COLLECTIONS.find((c) => c.slug === slug);
}
